name: efootball_stats_manager
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '^2.18.6'
dependencies:
  hive_flutter:
  states_rebuilder:
  dotted_border: ^2.0.0+2
  google_fonts:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_hooks: 0.18.5+1
  hooks_riverpod: 2.1.3
  go_router: 6.0.1
  intl: 0.17.0
  shared_preferences: 2.0.17
  supabase_flutter: 0.3.3
  uni_links: 0.5.1
  validators: 3.0.0
  riverpod_annotation:
  json_annotation:
  # dartz:
  # fpdart:
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  freezed_annotation: ^2.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_flavorizr: 2.1.5
  freezed: 2.3.2
  json_serializable: 6.6.0
  very_good_analysis: 3.1.0
  riverpod_generator: 1.1.1
  build_runner: 
  mockito: 5.3.2
  isar_generator: ^3.0.5
  flutter_lints:
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
